### Create
POST localhost:8080/api/pessimistic-lock/wallet


### Get all
GET localhost:8080/api/pessimistic-lock/wallet/all/1


### Purch
POST localhost:8080/api/pessimistic-lock/purchase
Content-Type: application/json

{
  "name": "Test",
  "price": 1,
  "walletId": 1
}
